# generated by datamodel-codegen:
#   filename:  config.json

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel


class UnitSystem(BaseModel):
    length: str
    accumulated_precipitation: str
    mass: str
    pressure: str
    temperature: str
    volume: str
    wind_speed: str


class Config(BaseModel):
    latitude: float
    longitude: float
    elevation: int
    unit_system: UnitSystem
    location_name: str
    time_zone: str
    components: list
    config_dir: str
    whitelist_external_dirs: list
    allowlist_external_dirs: list
    allowlist_external_urls: list
    version: str
    config_source: str
    safe_mode: bool
    state: str
    external_url: Optional[str] = None
    internal_url: Optional[str] = None
    currency: str
