# generated by datamodel-codegen:
#   filename:  request.json

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, Extra, Field


class Request(BaseModel):
    """
    Request
    """

    class Config:
        extra = Extra.allow

    id: str = Field(..., description="Message ID")
    data: dict[str, Any] = Field(..., description="Data")
