# generated by datamodel-codegen:
#   filename:  response.json

from __future__ import annotations

from typing import Any, Optional

from pydantic import BaseModel, Extra, Field


class Response(BaseModel):
    """
    Response
    """

    class Config:
        extra = Extra.allow

    id: str = Field(..., description="Message ID")
    data: Optional[dict[str, Any]] = Field(None, description="Data")
