---
name: Lint

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  lint-black-module:
    uses: timmo001/workflows/.github/workflows/lint-black.yml@master
    with:
      code-path: module
  lint-jsonlint:
    uses: timmo001/workflows/.github/workflows/lint-jsonlint.yml@master
  lint-markdown-links:
    uses: timmo001/workflows/.github/workflows/lint-markdown-links.yml@master
  lint-markdownlint:
    uses: timmo001/workflows/.github/workflows/lint-markdownlint.yml@master
  lint-prettier:
    uses: timmo001/workflows/.github/workflows/lint-prettier.yml@master
  lint-pylint-module:
    uses: timmo001/workflows/.github/workflows/lint-pylint.yml@master
    with:
      code-path: module
      module-name: timmopytemplate
  lint-yamllint:
    uses: timmo001/workflows/.github/workflows/lint-yamllint.yml@master
